using ExampleService.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ExampleService.Infrastructure.Data.Config
{
    /// <summary>
    /// Example Customer EF configuration. Probably best to let this get generated by EF and adjust where needed
    /// </summary>
    public class CustomerConfiguration : IEntityTypeConfiguration<Customer>
    {
        public void Configure(EntityTypeBuilder<Customer> builder)
        {
            builder.HasKey(e => e.Id)
                    .HasName("PRIMARY");

            builder.ToTable("customer");

            builder.Property(e => e.Id)
                    .HasColumnName("Id")
                    .HasColumnType("int unsigned");

            builder.Property(e => e.FirstName)
                    .HasColumnName("FirstName")
                    .HasMaxLength(45)
                    .IsUnicode(false);

            builder.Property(e => e.LastName)
                    .HasColumnName("LastName")
                    .HasMaxLength(45)
                    .IsUnicode(false);
        }
    }
}
